
import "./globals.css";
import Header from '@/components/ui/header/header'
import Footer from '@/components/ui/footer/footer'

export const metadata = {
  title: "متروگو",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
  manifest: "/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html className=" dark:bg-slate-950 bg-slate-50 scroll-smooth" lang="en">

      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
