name: Test and Format Code with Multiple Python Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format code with Ruff
      run: ruff format .

    - name: Run unit tests
      run: python -m unittest discover -s test -p "test_*.py"

