name: Run Tests

on:
  push:
    branches:
      - main  # یا هر شاخه‌ای که می‌خواهید بررسی شود

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # یا نسخه پایتون مورد نظر

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # اگر فایل requirements دارید

    - name: Run Tests
      run: |
        python Core/test.py
